@hostname = http://localhost
@port = 3003
@baseUrl = {{hostname}}:{{port}}/api/conductores

GET {{baseUrl}}/createindex HTTP/1.1

###
GET {{baseUrl}}/
###
GET {{baseUrl}}/5ed22abc3ed9101e9e8a3790
###
GET {{baseUrl}}/dni/V10292569

###
POST {{baseUrl}}/
Content-Type: application/json

{
  "dni": "ext548 56 r ",
  "nombre": "Extrangero",
  "activo": true,
  "ubicacion": {
    "direccion": "ssssdsdsdsd",
    "email":"epepe@gmail.com",
    "telefono": [{"casa": "223322"},{"cel":"+052-3287382"}]
  }
}

###
DELETE {{baseUrl}}/5ed22d69d2cc4321305c6b85

###
PUT {{baseUrl}}/5ed10c90a01e7f54a604107f
Content-Type: application/json

{
  "dni": 555444,
  "nombre": "JUAN CALIMERO",
  "activo": true,
  "ubicacion": {
    "direccion": "ssssdsdsdsd",
    "email":"epepe@gmail.com",
    "telefono": [{"casa": "223322"},{"cel":"+052-3287382"}]
  }
}