@hostname = http://localhost
@port = 3003
@baseUrl = {{hostname}}:{{port}}/api/conductores

GET {{baseUrl}}/createindex HTTP/1.1

###
GET {{baseUrl}}/
###
GET {{baseUrl}}/5ed230ca012e8a23d2a3afef
###
GET {{baseUrl}}/dni/V10292569

###
POST {{baseUrl}}/
Content-Type: application/json

{
  "dni": "ext548 56 r ",
  "nombre": "Extrangero",
  "imagenid": "3232323",
  "activo": true,
  "telefonohogar": "09320909093223",
  "telefonocelular": "09320909093223",
  "direccion": "ssssdsdsdsd",
  "email":"epepe@gmail.com"  
}

###
DELETE {{baseUrl}}/5ed22d69d2cc4321305c6b85

###
PUT {{baseUrl}}/5ed230ca012e8a23d2a3afef
Content-Type: application/json

{
  "dni": 10555444,
  "nombre": "JUAN CURRUTACO CALIMERO",
  "imagenid": "3232323",
  "activo": true,
  "telefonohogar": "09320909093223",
  "telefonocelular": "09320909093223",
  "direccion": "ssssdsdsdsd",
  "email":"epepe@gmail.com"
}