

GET http://localhost:3003/api/users/5ed0609251dd334e51359408

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "login": "juan",
  "pass": "12234",
  "email": "obando@gmail.com",
  "dni": "3232323",
  "name":"pedro obando"
}

###
GET http://localhost:3003/api/conductores

###
POST http://localhost:3003/api/conductores
Content-Type: application/json

{
  "dni": "2121212",
  "nombre": "pedro",
  "activo": true

}

###
DELETE http://localhost:3003/api/conductores/5ed06e6ed3ef175266fe52cc

