

POST http://localhost:3003/api/users
content-Type: application/json
{
  "name": "sample",
  "time": "Wed, 21 Oct 2015 18:27:50 GMT",
  "login": "pepe",
  "pass": "dsdsd",
  "email": "obando@gmail.com",
  "website": "sdsdsd",
  "dni": "3232323",
  "name":"pedro obando",
  "lastlogin": "dsdsdsd"
}

GET http://localhost:3003/api/users