@hostname = http://localhost
@port = 3003
@baseUrl = {{hostname}}:{{port}}/api/productos

GET {{baseUrl}}/createindex HTTP/1.1

###
GET {{baseUrl}}/

###
GET {{baseUrl}}/5ed2231db7fb061996800138

###
GET {{baseUrl}}/codigo/soya57

###
POST {{baseUrl}}/
Content-Type: application/json

{
  "codigo": "SOYA57",
  "nombre": "SALSA DE SOYA 57",
  "presentacion": "UND",
  "peso": 3,
  "activo": true
}

###
DELETE {{baseUrl}}/5ed16caff50b267f5406cf1a

###
PUT {{baseUrl}}/5ed2231db7fb061996800138
Content-Type: application/json

{
  "codigo": "c2cg3223x",
  "nombre": "Mayonesa Castillo",
  "presentacion": "LTS",
  "peso": 500,
  "activo": true
}