

@hostname = http://localhost
@port = 3003
@baseUrl = {{hostname}}:{{port}}/api/users

GET {{baseUrl}}/createindex HTTP/1.1

###
GET {{baseUrl}}/

###
POST {{baseUrl}}/
Content-Type: application/json

{
  "login": "antonio",
  "pass": "12234",
  "email": "antoniomartinez@gmail.com",
  "nombre": "Antonio Martinez",
  "roll": "Administrador"
}

###
DELETE {{baseUrl}}/5ed12ff348ef18720892e83e

###
PUT {{baseUrl}}/5ed769c4d829ab001bab0582
Content-Type: application/json

{
  "login": "carlosmanuel",
  "pass": "X123",
  "email": "sami@yahoo.com",
  "nombre": "Samuel moncada",
  "roll": "usuario"
}
