

@hostname = http://localhost
@port = 3003
@baseUrl = {{hostname}}:{{port}}/api/users

GET {{baseUrl}}/createindex HTTP/1.1

###
GET {{baseUrl}}/

###
POST {{baseUrl}}/
Content-Type: application/json

{
  "login": "antonio",
  "pass": "12234",
  "email": "antoniomartinez@gmail.com",
  "nombre": "Antonio Martinez",
  "roll": "Administrador"
}

###
DELETE {{baseUrl}}/5ed12ff348ef18720892e83e

###
PUT {{baseUrl}}/5ed0cf6aefe78b1197e5bf84
Content-Type: application/json

{
"login": "abertsaa",
"pass": "2525641",
"email": "albertocortez@hotmail.com.ve",
"nombre": "Aberto Cortez",
"roll": "usuario",
"imagenid": "5ee90832e219e0001b56b0d3"
}
